### PR TITLE
cutted content-type value

### PR DESCRIPTION
**Pull request by patryksz**
requests sent from firefox are enriched with Content-type header contains value after semicolon

### CODE REVIEW

**Comment by Eyjafjallajokull** [comment]
Have you tested this change with value without semicolon? I think `substr($contentType, 0, false);` will return empty string.

**Comment by patryksz** [comment]
omg, i forgot about this case. I've added few lines.

**Comment by Eyjafjallajokull** [comment]
Thanks for contribution ;)

**Comment by patryksz** [comment]
my pleasure ; )

**Pull request merged**
